apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quayecosystem4
  namespace: quay-enterprise
spec:
  quay:
    enableRepoMirroring: true
    keepConfigDeployment: true
    externalAccess:
      hostname: quay4.apps.cluster-4780.4780.example.opentlc.com
      tls:
        termination: edge
      type: Route
    database:
      volumeSize: 10Gi
    imagePullSecretName: dummy-pull-secret
    registryStorage:
      persistentVolumeAccessModes:
        - ReadWriteOnce
    persistentVolumeSize: 10Gi
    securityContext:
      fsGroup: 1001
  clair:
    enabled: true
    imagePullSecretName: dummy-pull-secret
